=== overwraith/Cameron-Block_Examples/Web Scripting/Assignment 10.2/Cars_Definition.dtd
<?xml version = "1.0" encoding = "utf-8"?>
<!-- Author: Cameron Block 
     Class: CIS 337 Web Scripting
     File: Cars_Definition.dtd
     Purpose: The Data Type Diagram for the cars XML class. 
     -->

<!ELEMENT Car_Catalog (Car*)>
<!ELEMENT Car (make, model, year, color, engine, number_of_doors, transmission_type, accessories)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT engine (number_of_cylinders, fuel_system)>
<!ELEMENT number_of_doors (#PCDATA)>
<!ELEMENT transmission_type (#PCDATA)>

<!-- Accessories element contains the following attributes. -->
<!ELEMENT accessories (#PCDATA)>
<!ATTLIST accessories
	radio (yes | no) #REQUIRED
	air_conditioning (yes | no) #REQUIRED
	power_windows (yes | no) #REQUIRED
	power_steering (yes | no) #REQUIRED
	power_brakes (yes | no) #REQUIRED>

<!-- Nested element types. -->
<!ELEMENT number_of_cylinders (#PCDATA)>
<!ELEMENT fuel_system (#PCDATA)>

=== overwraith/Cameron-Block_Examples/Web Scripting/Assignment 6.2/Car_Catalog.xml
<?xml version = "1.0" encoding = "utf-8"?>

<!-- Author: Cameron Block 
     Class: CIS 337 Web Scripting
     File: Car_Catalog.xml
     Purpose: The Data Type Diagram for the cars XML class. 
     -->

<!DOCTYPE Car_Catalog SYSTEM "Cars_Definition.dtd">
<Car_Catalog>
	<Car>
		<make>Chevy</make>
		<model>Buick Century Custom</model>
		<year>2001</year>
		<color>Gold</color>
		<!-- Engine a composite type. -->
		<engine>
			<number_of_cylinders>6</number_of_cylinders>
			<fuel_system>Nuclear Fusion</fuel_system>
			<!-- I am a programmer, not an engineer! -->
		</engine>
		<number_of_doors>4</number_of_doors>
		<transmission_type>Automatic</transmission_type>
		<!-- Accessories has a lot of attributes-->
		<accessories 
			radio = "yes" 
			air_conditioning = "yes" 
			power_windows = "yes" 
			power_steering = "yes" 
			power_brakes = "yes">Full Package</accessories>
	</Car>
	<Car>
		<make>Chevi</make>
		<model>Malibu</model>
		<year>2001</year>
		<color>Maroon</color>
		<!-- Engine a composite type. -->
		<engine>
			<number_of_cylinders>6</number_of_cylinders>
			<fuel_system>Gas</fuel_system>
		</engine>
		<number_of_doors>4</number_of_doors>
		<transmission_type>Automatic</transmission_type>
		<!-- Accessories has a lot of attributes-->
		<accessories 
			radio = "yes" 
			air_conditioning = "yes" 
			power_windows = "yes" 
			power_steering = "yes" 
			power_brakes = "yes">Full Package</accessories>
	</Car>
	<Car>
		<make>Chevy</make>
		<model>Cobalt</model>
		<year>2008</year>
		<color>Blue</color>
		<!-- Engine a composite type. -->
		<engine>
			<number_of_cylinders>4</number_of_cylinders>
			<fuel_system>Gas</fuel_system>
		</engine>
		<number_of_doors>4</number_of_doors>
		<transmission_type>Automatic</transmission_type>
		<!-- Accessories has a lot of attributes-->
		<accessories 
			radio = "yes" 
			air_conditioning = "yes" 
			power_windows = "yes" 
			power_steering = "yes" 
			power_brakes = "yes">Full Package</accessories>
	</Car>
</Car_Catalog>
