=== overwraith/Cameron-Block_Examples/Web Scripting/Assignment 5.2/Cars_Definition.xsd
<?xml version = "1.0" encoding = "utf-8"?>
<!-- Author: Cameron Block 
     Class: CIS 337 Web Scripting
     File: Cars_Definition.xsd
     Purpose: The Data Type Diagram for the cars XML class. 
     -->

<xs:schema 
	xmlns:xs = "http://www.w3.org/2001/XMLSchema" 
	targetNamespace = "http://academic1.bellevue.edu/users/CIS33733/CarsXMLSchema"
  xmlns = "http://academic1.bellevue.edu/users/CIS33733/CarsXMLSchema"
	elementFormDefault = "qualified">
	
	<!-- Define Car_Catalog class. -->
	<xs:element name = "Car_Catalog">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Car" type = "Car" maxOccurs = "unbounded" minOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<!-- Define Car class. -->
	<xs:complexType name = "Car">
    <xs:sequence>
		  <xs:element name = "make" type = "xs:string"/>
		  <xs:element name = "model" type = "xs:string"/>
		  <xs:element name = "year" type = "xs:integer"/>
      <xs:element name = "color" type = "xs:string"/>
		  <!-- Nested element types. -->
		  <xs:element name = "engine" type = "engine"/>
		
		  <xs:element name = "number_of_doors" type = "xs:integer"/>
		  <xs:element name = "transmission_type" type = "xs:string"/>
		
		  <!-- Accessories element contains the following attributes. -->
      <xs:element name = "accessories">

        <xs:complexType>
          <xs:simpleContent>
            <!-- String content. -->
            <xs:extension base ="xs:string">
              <!-- Yes/No attributes. -->
              <xs:attribute name="radio" type="radio" use ="required"/>
              <xs:attribute name="air_conditioning" type="air_conditioning" use ="required"/>
              <xs:attribute name="power_windows" type="power_windows" use ="required"/>
              <xs:attribute name="power_steering" type="power_steering" use ="required"/>
              <xs:attribute name="power_brakes" type="power_brakes" use ="required"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>

      </xs:element>
    </xs:sequence>
	</xs:complexType>
	
	<!-- Define engine class. -->
	<xs:complexType name = "engine">
    <xs:sequence>
		  <xs:element name = "number_of_cylinders" type = "xs:integer"/>
		  <xs:element name = "fuel_system" type = "xs:string"/>
    </xs:sequence>
	</xs:complexType>
  
  
  <!-- Define the attributes to be used in the car class. -->
  <xs:simpleType name="radio">
    <xs:restriction base="xs:string">
      <xs:enumeration value ="yes"/>
      <xs:enumeration value ="no"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="air_conditioning">
    <xs:restriction base="xs:string">
      <xs:enumeration value ="yes"/>
        <xs:enumeration value ="no"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="power_windows">
    <xs:restriction base="xs:string">
      <xs:enumeration value ="yes"/>
      <xs:enumeration value ="no"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="power_steering">
    <xs:restriction base="xs:string">
      <xs:enumeration value ="yes"/>
      <xs:enumeration value ="no"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="power_brakes">
    <xs:restriction base="xs:string">
      <xs:enumeration value ="yes"/>
      <xs:enumeration value ="no"/>
    </xs:restriction>
  </xs:simpleType>
    
</xs:schema>

=== overwraith/Cameron-Block_Examples/Web Scripting/Assignment 10.2/Car_Catalog_2.xml
<?xml version = "1.0" encoding = "utf-8"?>

<!-- Author: Cameron Block 
     Class: CIS 337 Web Scripting
     File: Car_Catalog.xml
     Purpose: The Data Type Diagram for the cars XML class. 
     -->

<Car_Catalog 
	xmlns = "http://academic1.bellevue.edu/users/CIS33733/CarsXMLSchema"
	xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation = "http://academic1.bellevue.edu/users/CIS33733 Cars_Definition.xsd">
	<Car>
		<make>Chevy</make>
		<model>Buick Century Custom</model>
		<year>2001</year>
		<color>Gold</color>
		<!-- Engine a composite type. -->
		<engine>
			<number_of_cylinders>6</number_of_cylinders>
			<fuel_system>Nuclear Fusion</fuel_system>
			<!-- I am a programmer, not an engineer! -->
		</engine>
		<number_of_doors>4</number_of_doors>
		<transmission_type>Automatic</transmission_type>
		<!-- Accessories has a lot of attributes-->
		<accessories 
			radio = "yes" 
			air_conditioning = "yes" 
			power_windows = "yes" 
			power_steering = "yes" 
			power_brakes = "yes">Full Package</accessories>
	</Car>
	<Car>
		<make>Chevi</make>
		<model>Malibu</model>
		<year>2001</year>
		<color>Maroon</color>
		<!-- Engine a composite type. -->
		<engine>
			<number_of_cylinders>6</number_of_cylinders>
			<fuel_system>Gas</fuel_system>
		</engine>
		<number_of_doors>4</number_of_doors>
		<transmission_type>Automatic</transmission_type>
		<!-- Accessories has a lot of attributes-->
		<accessories 
			radio = "yes" 
			air_conditioning = "yes" 
			power_windows = "yes" 
			power_steering = "yes" 
			power_brakes = "yes">Full Package</accessories>
	</Car>
	<Car>
		<make>Chevy</make>
		<model>Cobalt</model>
		<year>2008</year>
		<color>Blue</color>
		<!-- Engine a composite type. -->
		<engine>
			<number_of_cylinders>4</number_of_cylinders>
			<fuel_system>Gas</fuel_system>
		</engine>
		<number_of_doors>4</number_of_doors>
		<transmission_type>Automatic</transmission_type>
		<!-- Accessories has a lot of attributes-->
		<accessories 
			radio = "yes" 
			air_conditioning = "yes" 
			power_windows = "yes" 
			power_steering = "yes" 
			power_brakes = "yes">Full Package</accessories>
	</Car>
</Car_Catalog>
